version: '3.8'

services:
  whalealert-bot:
    build: .
    container_name: whalealert-pro
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"